export const TRIPLET = 3
export const QUINTUPLET = 5
export const SEPTUPLET = 7
export const NONUPLET = 9

export const WHOLE = 0.5 * 2
export const WHOLE_TRIPLET = 0.5 * 3
export const HALF = 1 * 2
export const HALF_TRIPLET = 1 * 3
export const QUARTER = 2 * 2
export const QUARTER_TRIPLET = 2 * 3
export const EIGHTH = 4 * 2
export const EIGHTH_TRIPLET = 4 * 3
export const SIXTEENTH = 8 * 2
export const SIXTEENTH_TRIPLET = 8 * 3
export const THIRTY_SECOND = 16 * 2
export const THIRTY_SECOND_TRIPLET = 16 * 3

export const CHANCE_WHOLE = 100
export const CHANCE_WHOLE_TRIPLET = 1
export const CHANCE_HALF = 250
export const CHANCE_HALF_TRIPLET = 1
export const CHANCE_QUARTER = 5000
export const CHANCE_QUARTER_TRIPLET = 1
export const CHANCE_EIGHTH = 1000
export const CHANCE_EIGHTH_TRIPLET = 1
export const CHANCE_SIXTEENTH = 500
export const CHANCE_SIXTEENTH_TRIPLET = 1000
export const CHANCE_THIRTY_SECOND = 100
export const CHANCE_THIRTY_SECOND_TRIPLET = 100
